"""SYNTHETIC Suzuki-Miyaura fixture data. NOT experimental measurement.

Every yield value produced here is generated by a deterministic arithmetic
formula. None of it is a measurement, an estimate of a measurement, or derived
from any published dataset. It exists only so that the reaction-family adapter,
canonicalization, grouped splits, typed condition transfer, and the search /
final-evaluation protocol can be exercised locally while real Suzuki-Miyaura data
is unavailable.

No empirical Suzuki-Miyaura claim may be made from anything in this module.

The molecular structures are real and valid so that RDKit canonicalization is
genuinely exercised: real aryl halides, real boronic acids/esters/trifluoroborates,
real Pd sources, real phosphine ligands, real inorganic bases, and the correct
biaryl coupling product for each substrate pair.
"""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Any

import pandas as pd
import yaml

from bh_augmentation.data.reaction_family import (
    DatasetProvenance,
    ReactionFamilyAdapter,
    suzuki_miyaura_adapter,
)

FIXTURE_SCHEMA_NOTE = "synthetic-suzuki-fixture-not-measured-v1"

# (organohalide, organoboron, product) triples: each product is the correct
# cross-coupling product of its own substrate pair.
SUBSTRATE_PAIRS: tuple[tuple[str, str, str], ...] = (
    ("Brc1ccccc1", "OB(O)c1ccccc1", "c1ccc(-c2ccccc2)cc1"),
    ("Ic1ccc(C)cc1", "OB(O)c1ccc(OC)cc1", "COc1ccc(-c2ccc(C)cc2)cc1"),
    (
        "Clc1ccc(C(F)(F)F)cc1",
        "CC1(C)OB(OC1(C)C)c1ccccc1",
        "FC(F)(F)c1ccc(-c2ccccc2)cc1",
    ),
    ("Brc1cccnc1", "[K+].F[B-](F)(F)c1ccccc1", "c1ccc(-c2cccnc2)cc1"),
)

CATALYSTS: tuple[str, ...] = ("[Pd]", "Cl[Pd]Cl")
LIGANDS: tuple[str, ...] = (
    "c1ccc(P(c2ccccc2)c2ccccc2)cc1",
    "CC(C)P(C(C)C)C(C)C",
    "C1CCC(P(C2CCCCC2)C2CCCCC2)CC1",
)
BASES: tuple[str, ...] = (
    "O=C([O-])[O-].[K+].[K+]",
    "O=C([O-])[O-].[Cs+].[Cs+]",
    "O=P([O-])([O-])[O-].[K+].[K+].[K+]",
)
SOLVENTS: tuple[str, ...] = ("C1CCOC1", "CC(C)O", "COCCOC")


def suzuki_fixture_frame(n_rows: int = 72) -> pd.DataFrame:
    """Return the deterministic synthetic Suzuki fixture frame.

    The frame deliberately contains:

    * replicate rows whose canonical reaction is identical but whose synthetic
      yield differs, so grouped splitting has something to keep together;
    * one pair of rows written with different but chemically equivalent SMILES
      for the same boronic acid, so RDKit canonicalization is doing real work.
    """
    rows: list[dict[str, Any]] = []
    for index in range(n_rows):
        halide, boron, product = SUBSTRATE_PAIRS[index % len(SUBSTRATE_PAIRS)]
        catalyst = CATALYSTS[(index // 7) % len(CATALYSTS)]
        ligand = LIGANDS[(index // 4) % len(LIGANDS)]
        base = BASES[(index // 11) % len(BASES)]
        solvent = SOLVENTS[(index // 5) % len(SOLVENTS)]
        rows.append(
            _row(
                f"synthetic_suzuki_{index}",
                halide,
                boron,
                catalyst,
                ligand,
                base,
                solvent,
                product,
                _synthetic_yield(index),
            )
        )

    # Replicates of an existing canonical reaction with a different fake yield.
    for replicate in range(3):
        halide, boron, product = SUBSTRATE_PAIRS[0]
        rows.append(
            _row(
                f"synthetic_suzuki_replicate_{replicate}",
                halide,
                boron,
                CATALYSTS[0],
                LIGANDS[0],
                BASES[0],
                SOLVENTS[0],
                product,
                _synthetic_yield(1000 + replicate),
            )
        )

    # Chemically identical to the previous block, written differently on purpose:
    # 'c1ccccc1B(O)O' and 'OB(O)c1ccccc1' are the same molecule.
    halide, _, product = SUBSTRATE_PAIRS[0]
    rows.append(
        _row(
            "synthetic_suzuki_equivalent_smiles",
            halide,
            "c1ccccc1B(O)O",
            CATALYSTS[0],
            LIGANDS[0],
            BASES[0],
            SOLVENTS[0],
            product,
            _synthetic_yield(2000),
        )
    )
    return pd.DataFrame(rows)


def write_suzuki_fixture_csv(directory: Path, *, n_rows: int = 72) -> Path:
    """Write the synthetic fixture to ``directory`` and return its path."""
    path = Path(directory) / "synthetic_suzuki_fixture_NOT_MEASURED.csv"
    suzuki_fixture_frame(n_rows=n_rows).to_csv(path, index=False)
    return path


def suzuki_fixture_provenance(path: Path) -> DatasetProvenance:
    """Return provenance that states plainly that this data is not measured."""
    digest = hashlib.sha256(Path(path).read_bytes()).hexdigest()
    return DatasetProvenance(
        source_name="SYNTHETIC FIXTURE generated by tests/suzuki_fixture.py",
        source_url="local://tests/suzuki_fixture.py",
        license="Not applicable: generated fixture, contains no third-party data",
        citation=(
            "No citation: these are not experimental measurements. Yields are a "
            "deterministic arithmetic function of the row index."
        ),
        retrieved_date="not-applicable-generated-fixture",
        raw_file_sha256=digest,
    )


def suzuki_fixture_adapter(path: Path) -> ReactionFamilyAdapter:
    """Return the Suzuki adapter bound to the synthetic fixture's provenance."""
    return suzuki_miyaura_adapter(suzuki_fixture_provenance(path))


def suzuki_fixture_config(
    dataset_path: Path,
    output_directory: Path,
    *,
    n_bits: int = 64,
    seeds: list[int] | None = None,
) -> dict[str, Any]:
    """Return a complete, valid external-family config for the fixture."""
    provenance = suzuki_fixture_provenance(dataset_path)
    return {
        "scientific_run": True,
        "allow_hash_fingerprint_fallback": False,
        "reaction_family": {
            "family_id": "suzuki_miyaura",
            "transferable_roles": ["ligand", "base", "solvent_or_additive"],
            "provenance": provenance.to_dict(),
        },
        "canonicalization": {
            "backend": "rdkit",
            "isomeric_smiles": True,
            "preserve_role_order": True,
        },
        "dataset": {"path": str(dataset_path), "yield_column": "yield"},
        "splits": {
            "group_column": "canonical_reaction_key",
            "seeds": seeds or [0],
            "train_size": 0.6,
            "valid_size": 0.2,
            "test_size": 0.2,
            "train_fractions": [1.0],
        },
        "features": {
            "representation_kind": "suzuki_miyaura_role_separated",
            "n_bits": int(n_bits),
            "radius": 2,
            "fingerprint_backend": "rdkit",
        },
        "condition_transfer": {
            "enabled": True,
            "transferable_roles": ["ligand", "base", "solvent_or_additive"],
            "max_candidates_per_source": 2,
            "synthetic_multipliers": [0.5],
        },
        "selection": {"metric": "rmse", "lower_is_better": True},
        "output": {"directory": str(output_directory)},
    }


def write_suzuki_fixture_config(path: Path, config: dict[str, Any]) -> Path:
    """Write a fixture config to disk for CLI-style tests."""
    Path(path).write_text(yaml.safe_dump(config, sort_keys=False))
    return Path(path)


def _row(
    reaction_id: str,
    halide: str,
    boron: str,
    catalyst: str,
    ligand: str,
    base: str,
    solvent: str,
    product: str,
    synthetic_yield: float,
) -> dict[str, Any]:
    return {
        "reaction_id": reaction_id,
        "smiles_organohalide": halide,
        "smiles_organoboron": boron,
        "smiles_catalyst": catalyst,
        "smiles_ligand": ligand,
        "smiles_base": base,
        "smiles_solvent_or_additive": solvent,
        "smiles_product": product,
        "yield": float(synthetic_yield),
        "data_origin": FIXTURE_SCHEMA_NOTE,
    }


def _synthetic_yield(index: int) -> float:
    return float((index * 17 + 11) % 101)
